In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output
values=np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array=np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

4.43 s ± 38.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# UFuncs 소개

In [3]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
%timeit (1.0 / big_array)

6.98 ms ± 166 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
#백터화 연산으로 더 빠르게 연산을 수행한다
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
x=np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

# NumPy 유니버셜 함수(UFuncs)

In [7]:
x=np.arange(4)
print("x     = ",x)
print("x + 5 = ",x+5)
print("x - 5 = ",x-5)
print("x * 2 = ",x*2)
print("x / 2 = ",x/2)
print("x //2 = ",x//2)

x     =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x //2 =  [0 0 1 1]


In [8]:
print("-x     =",-x)
print("x ** 2 =", x**2)
print("x % 2  =",x%2 )

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


In [9]:
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [10]:
np.add(x,2)

array([2, 3, 4, 5])

In [11]:
#절댓값 함수
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [12]:
np.absolute(x)  # np.abs(X)

array([2, 1, 0, 1, 2])

In [13]:
#삼각함수
theta=np.linspace(0,np.pi,3)

In [14]:
print("theta      =",theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =",np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [15]:
#역삼각함수 또한 가능
x=[-1,0,1]
print("x         =",x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =",np.arccos(x))
print("arctan(x) =", np.arctan(x))

x         = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [16]:
#지수와 로그
x=[1,2,3]
print("x   =",x)
print("e^x =",np.exp(x))
print("2^x =",np.exp2(x))
print("3^x =",np.power(3,x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [17]:
x=[1,2,4,10]
print("x        =",x)
print("ln(x)    =",np.log(x))
print("log2(x)  =",np.log2(x))
print("log10(x) =",np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


# 고급 Ufunc 기능

In [18]:
#출력 지정
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [19]:
# 배열 뷰와 함께 사용 가능
#예를 들어, 연산 결과를 지정된 배열의 요소에 하나씩 건너뛰며 기록 가능
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [20]:
#집계
x=np.arange(1,6)
np.add.reduce(x)  #배열의 모든 요소의 합 반한

15

In [21]:
np.multiply.reduce(x)  #모든 배열 요소의 곱을 반환

120

In [22]:
#계산의 중간 결과를 모두 저장하고 싶다면 accumulate사용
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [23]:
#외적(Outer products)
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])