In [3]:
import numpy as np

In [4]:
#정수 배열
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
#넘파이의 경우 배열의 모든 요소가 같은 타입이어야 한다.
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
#명시적으로 데이터 타입을 설정 dtype
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
#리스트를 중첩하면 다차원 배열이 가능하다
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
#0으로 채운 배열
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#1로 채운 배열 (3x5배열)
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#3.14로 채운 배열
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
#선형 수열로 채운 배열
#내장함수임 range()와 유사
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#0과 1사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#균등하게 분포된 배열 만들기
#0과 1사이의 난수로 채움
np.random.random((3,3))

array([[0.14676044, 0.92583425, 0.3230679 ],
       [0.27680304, 0.59092731, 0.50586384],
       [0.88611352, 0.7872644 , 0.15340974]])

In [18]:
#정규분포(평균=0, 표준편차=1)위 난수로 채운 배열
np.random.normal(0,1,(3,3))

array([[-0.92186975,  0.38978719,  0.97095124],
       [ 0.42273039, -0.82556361,  0.67481317],
       [ 0.62218408, -0.5737066 ,  0.47781632]])

In [19]:
#[0,10]구간의 임의의 정수로 채운 배열
np.random.randint(0,10,(3,3))

array([[1, 4, 4],
       [1, 4, 0],
       [1, 5, 5]])

In [20]:
#3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# 세 개의 정수를 가지는 초기화되지 않은 배열
#값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])