In [1]:
import numpy as np

In [2]:
#정수 배열
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
#넘파이의 경우 배열의 모든 요소가 같은 타입이어야 한다.
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
#명시적으로 데이터 타입을 설정 dtype
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
#리스트를 중첩하면 다차원 배열이 가능하다
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
#0으로 채운 배열
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#1로 채운 배열 (3x5배열)
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#3.14로 채운 배열
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
#선형 수열로 채운 배열
#내장함수임 range()와 유사
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#0과 1사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#균등하게 분포된 배열 만들기
#0과 1사이의 난수로 채움
np.random.random((3,3))

array([[0.91986501, 0.02675145, 0.48147658],
       [0.11160751, 0.74676363, 0.03515099],
       [0.9077254 , 0.4469049 , 0.02290113]])

In [12]:
#정규분포(평균=0, 표준편차=1)위 난수로 채운 배열
np.random.normal(0,1,(3,3))

array([[-2.44647272, -1.3948259 ,  1.34638334],
       [-1.17991948,  1.72581534, -1.87096119],
       [-1.43694831,  0.24318944,  0.20865381]])

In [13]:
#[0,10]구간의 임의의 정수로 채운 배열
np.random.randint(0,10,(3,3))

array([[6, 9, 2],
       [6, 3, 4],
       [6, 0, 4]])

In [14]:
#3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# 세 개의 정수를 가지는 초기화되지 않은 배열
#값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])