# NumPy 배열 속성 지정

In [ ]:
import numpy as np
np.random.seed(0) #재현 가능성을 위한 시드 값
 
x1=np.random.randint(10,size=6)   #1차원 배열
x2=np.random.randint(10,size=(3,4))   #2차원 배열
x3=np.random.randint(10,size=(3,4,5))   #3차원 배열

In [3]:
print("x3 ndim: ", x3.ndim)   #차원의 개수
print("x3 shape: ", x3.shape) #각 차원의 크기
print("x3 size: ", x3.size)   #전체 배열 크기

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print("dtype:",x3.dtype)  #배열의 데이터 타입

dtype: int32


In [5]:
print("itemsize:",x3.itemsize,"bytes")  #각 배열 요소의 크기를 바이트 단위로 
print("nbytes:",x3.nbytes,"bytes")      #배열의 전체 크기를 바이트 단위로(=itemsize * size)

itemsize: 4 bytes
nbytes: 240 bytes


# 배열 인덱싱: 단일 요소에 접근하기 

In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
#배열의 i번째 값에 접근하려는 경우 
x1[0]

5

In [9]:
#배열의 끝에서부터 인덱싱 하는 경우 음수 인덱스를 사용
x1[-1]

9

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
#다차원 배열에서는 콤마로 구분된 인덱스 튜플을 이용
x2[0,0]

3

In [12]:
x2[2,-1]

7

In [13]:
#인덱스 표기법을 사용해 값을 수정 할 수 있다
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
#넘파이 배열은 고정 타입을 가진다는 점을 명시해야한다
#값을 수정할 경우에도 고정된 타입의 형태로 자동 수정된다
x1[0]=3.14159
x1

array([3, 0, 3, 3, 7, 9])

# 배열 슬라이싱: 하위 배열에 접근하기

In [16]:
#배열 x의 슬라이스에 접근하는 경우 
#x[start:stop:step]  default값으로 start=0, stop= 차원 크기,step=1
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]   #첫 다섯 개 요소

array([0, 1, 2, 3, 4])

In [18]:
x[5:]  #인덱스 5 다음 요소들

array([5, 6, 7, 8, 9])

In [19]:
x[4:7] #중간 하위 배열

array([4, 5, 6])

In [20]:
x[::2] #하나 걸러 하나씩의 요소로 구성된 배열

array([0, 2, 4, 6, 8])

In [21]:
x[1::2]  #인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열

array([1, 3, 5, 7, 9])

In [22]:
#step값이 음수일 경우 start와 stop의 기본값아 서로 바뀐다
x[::-1]  #모든 요소를 거꾸로 나열 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2]  #인덱스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열

array([5, 3, 1])

In [24]:
#다차원 하위 배열
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2[:2,:3] #두 개의 행 , 세 개의 열

array([[12,  5,  2],
       [ 7,  6,  8]])

In [28]:
x2[:3,::2]  #모든 행, 한 열 걸러 하나씩

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [29]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [30]:
print(x2[:,0]) #x2의 첫 번째 열

[12  7  1]


In [31]:
print(x2[0,:]) #x2의 첫 번째 행 x2[0]과 동일

[12  5  2  4]


In [32]:
#배열 슬라이스느 나배열 데이터의 사본이 아니라 뷰(view)를 반환한다
x2_sub=x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [34]:
#하위 배열을 수정할 경우 원래 배열이 변경 될 것이다
x2_sub[0,0]=99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
#명시적으로 배열을 복사하고 싶을 경우 copy()메서드 사용
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [37]:
#하위 배열을 수정해도 원래 배열이 그대로 유지된다
x2_sub_copy[0,0]=42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# 배열 재구조화

In [38]:
grid=np.arange(1,10).reshape((3,3))
print(grid)                            

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
x=np.array([1,2,3])
#reshape을 이용한 행 벡터
x.reshape((1,3))

array([[1, 2, 3]])

In [40]:
#newaxis를 이용한 행 벡터
x[np.newaxis,:]

array([[1, 2, 3]])

In [41]:
#reshape을 이용한 열 벡터
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [42]:
#newaxis를 이용한 열 벡터
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# 배열 연결 및 분할

In [43]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])  #튜플이나 배열의 리스트를 척 번쨰 인수로 취한다

array([1, 2, 3, 3, 2, 1])

In [45]:
z=[99,99,99]
print(np.concatenate([x,x,z]))  #한 번에 두 개 이상의 배열을 연결

[ 1  2  3  1  2  3 99 99 99]


In [46]:
#2차원 배열에서도 사용할 수 있다
grid=np.array([[1,2,3],
              [4,5,6]])

In [47]:
#첫 번째 축을 따라 연결
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
#두 번째 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
#혼합된 차원의 배열 이용
x=np.array([1,2,3])
grid=np.array([[9,8,7],
             [6,5,4]])
#배열을 수직으로 쌓음
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [50]:
#배열을 수평으로 쌓음
y=np.array([[99],
            [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [52]:
x=[1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])  #각 함수에 분할 지점을 알려주는 인덱스 목록 전달 가능
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [53]:
#N개의 분할점은 N+1개의 하위 배열을 만든다
grid=np.arange(16).reshape((4,4))
grid                          

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [55]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
